version: '3'
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: uchat
  web:
    image: uchat
    ports:
      - '5000:5000'
    networks:
      - webnet
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/uchat?schema=public
      REDIS_HOST: redis
    command: ['./wait-for-it.sh', 'db:5432', '--', './start-script.sh']
networks:
  webnet:
